# Generated by Django 3.1.2 on 2020-10-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('main_title', models.CharField(max_length=50, verbose_name='main_title')),
                ('sub_title', models.CharField(max_length=50, verbose_name='sub_title')),
                ('content', models.TextField()),
                ('article_type', models.IntegerField(choices=[(0, 'Python'), (1, 'FrontEnd'), (2, 'Other')], default=0)),
            ],
        ),
    ]
