# Generated by Django 3.1.2 on 2020-10-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='username')),
                ('tags', models.CharField(max_length=7, verbose_name='tags')),
                ('content', models.TextField()),
            ],
        ),
    ]
