# Generated by Django 3.1.2 on 2020-10-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_msg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Blog',
        ),
    ]
